#############################################################################
# Makefile for building: gvmepp
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  gvmepp.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o QMakefile.mk gvmepp.pro
#############################################################################

MAKEFILE      = QMakefile.mk

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../inc -Iinc -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gvmepp1.0.0
DISTDIR = /home/lrdprdx/projects/VME/gui/gvmepp/.tmp/gvmepp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/DeviceWindow.cpp \
		src/Dialogs.cpp \
		src/main.cpp \
		src/SlaveWindow.cpp \
		src/Style.cpp \
		src/V2718Window.cpp \
		src/V6533NWindow.cpp \
		src/V895Window.cpp moc_DeviceWindow.cpp \
		moc_Dialogs.cpp \
		moc_SlaveWindow.cpp \
		moc_Style.cpp \
		moc_V2718Window.cpp \
		moc_V6533NWindow.cpp \
		moc_V895Window.cpp
OBJECTS       = DeviceWindow.o \
		Dialogs.o \
		main.o \
		SlaveWindow.o \
		Style.o \
		V2718Window.o \
		V6533NWindow.o \
		V895Window.o \
		moc_DeviceWindow.o \
		moc_Dialogs.o \
		moc_SlaveWindow.o \
		moc_Style.o \
		moc_V2718Window.o \
		moc_V6533NWindow.o \
		moc_V895Window.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gvmepp.pro inc/DeviceWindow.h \
		inc/Dialogs.h \
		inc/Prelude.h \
		inc/SlaveWindow.h \
		inc/Style.h \
		inc/V2718Window.h \
		inc/V6533NWindow.h \
		inc/V895Window.h src/DeviceWindow.cpp \
		src/Dialogs.cpp \
		src/main.cpp \
		src/SlaveWindow.cpp \
		src/Style.cpp \
		src/V2718Window.cpp \
		src/V6533NWindow.cpp \
		src/V895Window.cpp
QMAKE_TARGET  = gvmepp
DESTDIR       = 
TARGET        = gvmepp


first: all
####### Build rules

gvmepp:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

QMakefile.mk: gvmepp.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gvmepp.pro
	$(QMAKE) -o QMakefile.mk gvmepp.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
gvmepp.pro:
qmake: FORCE
	@$(QMAKE) -o QMakefile.mk gvmepp.pro

qmake_all: FORCE


all: QMakefile.mk gvmepp

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents inc/DeviceWindow.h inc/Dialogs.h inc/Prelude.h inc/SlaveWindow.h inc/Style.h inc/V2718Window.h inc/V6533NWindow.h inc/V895Window.h $(DISTDIR)/
	$(COPY_FILE) --parents src/DeviceWindow.cpp src/Dialogs.cpp src/main.cpp src/SlaveWindow.cpp src/Style.cpp src/V2718Window.cpp src/V6533NWindow.cpp src/V895Window.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) QMakefile.mk


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_DeviceWindow.cpp moc_Dialogs.cpp moc_SlaveWindow.cpp moc_Style.cpp moc_V2718Window.cpp moc_V6533NWindow.cpp moc_V895Window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DeviceWindow.cpp moc_Dialogs.cpp moc_SlaveWindow.cpp moc_Style.cpp moc_V2718Window.cpp moc_V6533NWindow.cpp moc_V895Window.cpp
moc_DeviceWindow.cpp: inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/DeviceWindow.h -o moc_DeviceWindow.cpp

moc_Dialogs.cpp: inc/Dialogs.h \
		inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/Dialogs.h -o moc_Dialogs.cpp

moc_SlaveWindow.cpp: inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/SlaveWindow.h -o moc_SlaveWindow.cpp

moc_Style.cpp: inc/Style.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/Style.h -o moc_Style.cpp

moc_V2718Window.cpp: inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/V2718Window.h -o moc_V2718Window.cpp

moc_V6533NWindow.cpp: inc/V6533NWindow.h \
		../../inc/modules/V6533N.h \
		../../inc/VSlave.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/modules/V895.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/V6533NWindow.h -o moc_V6533NWindow.cpp

moc_V895Window.cpp: inc/V895Window.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/modules/V6533N.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lrdprdx/projects/VME/gui/gvmepp/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lrdprdx/projects/VME/gui/gvmepp -I/home/lrdprdx/projects/VME/inc -I/home/lrdprdx/projects/VME/gui/gvmepp/inc -I/home/lrdprdx/projects/VME/gui/gvmepp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/csi/Tools/CAEN/CAENOO/inc -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include inc/V895Window.h -o moc_V895Window.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

DeviceWindow.o: src/DeviceWindow.cpp ../../inc/VException.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/Dialogs.h \
		inc/Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeviceWindow.o src/DeviceWindow.cpp

Dialogs.o: src/Dialogs.cpp inc/Dialogs.h \
		inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/Style.h \
		inc/V895Window.h \
		inc/V6533NWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dialogs.o src/Dialogs.cpp

main.o: src/main.cpp inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

SlaveWindow.o: src/SlaveWindow.cpp inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/V2718Window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SlaveWindow.o src/SlaveWindow.cpp

Style.o: src/Style.cpp inc/Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Style.o src/Style.cpp

V2718Window.o: src/V2718Window.cpp inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/Dialogs.h \
		inc/Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V2718Window.o src/V2718Window.cpp

V6533NWindow.o: src/V6533NWindow.cpp inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/V6533NWindow.h \
		inc/Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V6533NWindow.o src/V6533NWindow.cpp

V895Window.o: src/V895Window.cpp inc/V2718Window.h \
		inc/SlaveWindow.h \
		inc/DeviceWindow.h \
		inc/Prelude.h \
		../../inc/modules/V2718.h \
		../../inc/VController.h \
		../../inc/VArbiter.h \
		../../inc/VMaster.h \
		../../inc/VRequester.h \
		../../inc/VInterruptHandler.h \
		../../inc/UConfigurable.h \
		../../inc/VException.h \
		../../inc/modules/V895.h \
		../../inc/VSlave.h \
		../../inc/modules/V6533N.h \
		inc/V895Window.h \
		inc/Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V895Window.o src/V895Window.cpp

moc_DeviceWindow.o: moc_DeviceWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DeviceWindow.o moc_DeviceWindow.cpp

moc_Dialogs.o: moc_Dialogs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Dialogs.o moc_Dialogs.cpp

moc_SlaveWindow.o: moc_SlaveWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SlaveWindow.o moc_SlaveWindow.cpp

moc_Style.o: moc_Style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Style.o moc_Style.cpp

moc_V2718Window.o: moc_V2718Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_V2718Window.o moc_V2718Window.cpp

moc_V6533NWindow.o: moc_V6533NWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_V6533NWindow.o moc_V6533NWindow.cpp

moc_V895Window.o: moc_V895Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_V895Window.o moc_V895Window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

